# Generated by Django 3.0 on 2025-07-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_delete_address_and_letting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
